version: 1.0.{build}
branches:
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\ags-choco-pkg

build_script:
  - choco pack
  - choco install ags -y -s . 
  - choco uninstall ags -y -s .
